### ISSUE TITLE
Remove flattened query in ShareCredentials component.

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/bedrock-vue-wallet#55]
Flattened query should be removed. We must be able to process query as-is to properly apply and-or logic to results.

**Comment by dlongley** [comment]
See: https://github.com/digitalbazaar/bedrock-vue-wallet/pull/44#discussion_r1270223398

**Comment by dlongley** [comment]
Closing to replace with better UI-related issue. This has been partially addressed by PR #79.
