### ISSUE TITLE
Simplified wallet header should be rendered in CHAPI handler windows

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vue-wallet#74]
It looks like there's no header at all at the moment.

**Comment by jameseaster** [comment]
@dlongley 

So this looks very intentionally hidden in the WalletLayout.vue component:

```html
<template>
  <q-layout
    view="hHh LpR fFf"
    class="s-page">
    <q-header
      v-if="ready && !chapi" // <--- IF CHAPI IS FALSE, SHOW HEADER //
      class="shadow-3">
      <wallet-header
        :account="account"
        :logout="logout"
        :toggle-drawer="toggleDrawer" />
    </q-header>

    ...continuation of WalletLayout.vue component
```

<br />

This prop is passed in router.js on line 19 and 26 as true to hide the app header.

```javascript
/*!
 * Copyright (c) 2022-2023 Digital Bazaar, Inc. All rights reserved.
 */
import * as brQuasar from '@bedrock/quasar';
import {config} from '@bedrock/web';
import {Quasar} from 'quasar';
import {rootData} from './rootData.js';
import {session} from '@bedrock/web-session';

// all supported features in the current version of this lib
const FEATURES = new Map([
  ['/credential-handler', ({routeConfig}) => ({
    routes: [{
      name: 'credential-handler-register',
      path: `${routeConfig.path}/register`,
      component: () => import(
        /* webpackChunkName: "bedrock-vue-wallet-register" */
        '../routes/RegisterPage.vue'),
      meta: {title: 'Register', chapi: true} // <-------------------------- HERE //
    }, {
      name: 'credential-handler-exchange',
      path: `${routeConfig.path}/exchange`,
      component: () => import(
        /* webpackChunkName: "bedrock-vue-wallet-credential-handler" */
        '../routes/ChapiExchangePage.vue'),
      meta: {title: 'Exchange', chapi: true} // <------------------------- AND HERE //
    }]
  })],

  ...continuation of route.js file
```

<br />

Are we wanting to show the header and hide the drawer options? If we change the chapi prop to false then the header shows up, but so do the navigation options in the drawer, which may be exactly what we want. Just double checking the desired outcome of this issue.

> CHAPI handler window (while signed in to veres wallet)
>
> <img src="https://github.com/digitalbazaar/bedrock-vue-wallet/assets/56396286/6fa4465e-6813-4e1c-905d-24287235b239" alt="screenshot1" width="600" />

<br />

> CHAPI handler window with navigation drawer opened
>
> <img src="https://github.com/digitalbazaar/bedrock-vue-wallet/assets/56396286/ea7ec174-adc5-460e-acb0-305f7cd467de" alt="screenshot1" width="600" />

**Comment by dlongley** [comment]
I think we want to hide the drawer, we just want the header -- and it shouldn't be clickable such that it takes someone out of the flow somewhere else.

As for it being hidden previously, I think that was based on an assumption that the flow would happen within an iframe, but that's never the case now (and *sometimes* wasn't the case before, but most of the time it was).

**Comment by jameseaster** [comment]
@dlongley Right on, so render the header with the application logo and name, but make it non-clickable and without any navigation (drawer) options?

**Comment by dlongley** [comment]
@jameseaster, yes, that sounds right to me.
